name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Python 3.9 Webapp Slim
        id: docker_build_slim
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./3.9/webapp/slim/
          tags: codingforentrepreneurs/python:3.9-webapp-slim
      - name: Build and push Python 3.9 Webapp with Chromedriver
        id: docker_build_chromedriver
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./3.9/webapp/chromedriver/
          tags: codingforentrepreneurs/python:3.9-webapp-chromedriver
      - name: Build and push Python 3.9 Webapp with Chromedriver & Selenium
        id: docker_build_selenium
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./3.9/webapp/selenium/
          tags: codingforentrepreneurs/python:3.9-webapp-selenium
      - name: Build and push Python 3.9 Webapp with Cassandra, Chromedriver & Selenium
        id: docker_build_cassandra_selenium
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./3.9/webapp/cassandra-selenium/
          tags: codingforentrepreneurs/python:3.9-webapp-cassandra-selenium
